# Window settings
window:
  dimensions:
   columns: 140
   lines: 38
  padding:
   x: 4
   y: 4
  dynamic_padding: true # false
  decorations: buttonless # none, full, transparent, buttonless
scrolling:
  history: 10000
  multiplier: 3
background_opacity: 1.0

# Fonts settings
font:
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  size: 14.0
  offset:
   x: 0
   y: 0
  glyph_offset:
   x: 0
   y: 0

draw_bold_text_with_bright_colors: true

# Colors: Dracula
colors:
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'
    bright_foreground: '#ffffff'
  search:
    matches:
      foreground: '#44475a'
      background: '#50fa7b'
    focused_match:
      foreground: '#44475a'
      background: '#ffb86c'
    bar:
      background: '#282a36'
      foreground: '#f8f8f2'
  hints:
    start:
      foreground: '#282a36'
      background: '#f1fa8c'
    end:
      foreground: '#f1fa8c'
      background: '#282a36'
  selection:
    text: CellForeground
    background: '#44475a'
  normal:
    black: '#21222c'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#bd93f9'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#f8f8f2'
  bright:
    black: '#6272a4'
    red: '#ff6e6e'
    green: '#69ff94'
    yellow: '#ffffa5'
    blue: '#d6acff'
    magenta: '#ff92df'
    cyan: '#a4ffff'
    white: '#ffffff'

selection:
  save_to_clipboard: true 

cursor:
  style:
    shape: Block
    blinking: On
    unfocused_hollow: true

live_config_reload: true

# Key Binddings
key_bindings:
  - { key: N,             mods: Control|Shift,              action: SpawnNewInstance      }
  - { key: F,             mods: Alt,                        chars: "\x1bf"                }
  - { key: B,             mods: Alt,                        chars: "\x1bb"                }
