[general]
import = ["~/.config/alacritty/themes/themes/dracula.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_padding = true
blur = true
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 140
lines = 38

# [window.padding]
# x = 4
# y = 4
