# Tokyo Night Storm

# Font
font_family MesloLGS Nerd Font Mono
font_size   14.0

# Window
initial_window_width  140c
initial_window_height 40c
remember_window_size  no
scrollback_lines      100000
window_padding_width  4

# Selection
copy_on_select yes

# macOS
macos_option_as_alt left

# Remote control (required by smart-splits.nvim)
allow_remote_control socket-only
listen_on            unix:/tmp/kitty

# Tabs
tab_bar_edge         top
tab_bar_style        powerline
tab_powerline_style  angled

# Splits
enabled_layouts splits:split_axis=vertical
map cmd+d       launch --location=vsplit --cwd=current
map cmd+shift+d launch --location=hsplit --cwd=current
map cmd+alt+left  neighboring_window left
map cmd+alt+right neighboring_window right
map cmd+alt+up    neighboring_window up
map cmd+alt+down  neighboring_window down
map cmd+shift+w   close_window

# Tab shortcuts
map cmd+t     new_tab_with_cwd
map cmd+left  previous_tab
map cmd+right next_tab
map cmd+1     goto_tab 1
map cmd+2     goto_tab 2
map cmd+3     goto_tab 3
map cmd+4     goto_tab 4
map cmd+5     goto_tab 5
map cmd+6     goto_tab 6
map cmd+7     goto_tab 7
map cmd+8     goto_tab 8
map cmd+9     goto_tab 9

map cmd+k clear_terminal scrollback active
map cmd+f show_scrollback

# Colors
foreground           #C0CAF5
background           #24283B
selection_foreground #C0CAF5
selection_background #3658A0
cursor               #C0CAF5

# black
color0  #1D202F
color8  #414868
# red
color1  #F7768E
color9  #F7768E
# green
color2  #9ECE6A
color10 #9ECE6A
# yellow
color3  #E0AF68
color11 #E0AF68
# blue
color4  #7AA2F7
color12 #7AA2F7
# magenta
color5  #BB9AF7
color13 #BB9AF7
# cyan
color6  #7DCFFF
color14 #7DCFFF
# white
color7  #A9B1D6
color15 #C0CAF5
