# Tools directly used by the tracked shell/editor/tmux configuration.
brew "atuin"
brew "beautysh"
brew "coreutils"
brew "direnv"
brew "git-lfs"
brew "lazygit"
brew "neovim"
brew "shellcheck"
brew "tmux"
brew "zoxide"
