## enable or disable automatic sync
auto_sync = true

## which search mode to use
## possible values: prefix, fulltext, fuzzy
search_mode = "fuzzy"

## which style to use
## possible values: auto, full, compact
style = "compact"
