matches:
  - trigger: ":cuda"
    replace: "CUDA_VISIBLE_DEVICES="

  - trigger: ":zettel"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%Y%m%d%H%M%S"

  - trigger: ":date"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":time"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M"

  - trigger: ":now"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%Y-%m-%d %H:%d"

  - trigger: ":passwd"
    replace: "{{passwd}}"
    vars:
      - name: passwd
        type: shell
        params:
          cmd: "security find-generic-password -w -s 'espanso-cli' -a 'espanso'"

  - trigger: ":ai1"
    replace: |
      作为资深研究者，请使用中文和Markdown格式对论文进行结构化总结。具体要求如下：
      Summary: 用一两句话概括论文的核心内容。

      1. 🌐 **研究动机与关键科学问题**

      2. 📚 **背景与问题陈述**

      3. 🔑 **关键术语和定义**

      4. 🛠️ **方法**：
       - 分析方法的框架和流程，并比较与传统方法的差异。
       
      5. 📊 **实验设计**：
       - 说明使用的数据、基线和评价指标。
       
      6. 🔍 **核心结果**：
       - 以表格形式展示关键数据，使用加粗字体突出优势项。
       - 其他关键结果列点式罗列。
       
      7. 💡 **创新与贡献**：
       - 评估研究在理论和应用方面的创新性。
       - 说明研究对学术和实践的贡献。
       
      8. 📝 **局限性与潜在争议**：
       - 明确指出研究的几处局限性及可能的争议点。
       
      9. 📚 **未来研究及参考文献**：
       - 推测可能推动的未来研究方向。
       - 推荐若干相关参考文献，并附上推荐理由。

      注意事项：
      - 技术术语保留英文原文。
      - 参考文献保留英文原文。
      - Markdown语法无需使用分割线。
      - 如果涉及数据集，请指明数据集是否开源。
